apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-prod-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # Generate params that we can reference from app definitions in apps/*/app.yaml
    - git:
        repoURL: https://github.com/smooti/platform-services.git
        revision: HEAD
        files:
          - path: apps/*/app.yaml
  template:
    metadata:
      name: '{{.path.basename}}-prod'
    spec:
      project: platform

      sources:
        # Chart Git repo
        - repoURL: '{{.chart.repoURL}}'
          chart: '{{.chart.name}}'
          targetRevision: '{{.chart.version}}'
          helm:
            releaseName: '{{.path.basename}}'
            valueFiles:
              - $values/apps/{{.path.basename}}/common/common-values.yaml
              - $values/apps/{{.path.basename}}/environments/local-prod/default-env-values.yaml

        # Values Git repo (THIS defines $values)
        - repoURL: https://github.com/smooti/platform-services.git
          targetRevision: HEAD
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      